# Generated by Django 5.1.5 on 2025-02-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_multilanguage_faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Answer in Bengali'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Answer in Hindi'),
        ),
    ]
